#!/usr/bin/env pwsh
# patch-drop-generated-cmakelists.ps1
#
# Stops committing generated/CMakeLists.txt (a build artifact -- CppLogicMake's
# output, not source), restores the hand-written cmake/ThirdParty.cmake, and
# updates README.md / s.ps1 so CppLogicMake is documented as a hard build
# requirement instead of an optional fallback.
#
# Run from the repo root:  .\patch-drop-generated-cmakelists.ps1
# Then review with 'git diff' / 'git status' before committing.

$ErrorActionPreference = "Stop"

if (-not (Test-Path ".git")) {
    throw "Run this from the CppProcMon repo root (no .git found here)."
}

Write-Host "1. Restoring cmake/ThirdParty.cmake..." -ForegroundColor Cyan
git checkout -- cmake/ThirdParty.cmake

Write-Host "2. Gitignoring generated/ and staging the deletion..." -ForegroundColor Cyan
$gitignoreText = if (Test-Path .gitignore) { Get-Content .gitignore -Raw } else { "" }
if ($gitignoreText -notmatch [regex]::Escape("generated/")) {
    Add-Content .gitignore "`ngenerated/"
}
if (Test-Path generated/CMakeLists.txt) {
    git rm --cached generated/CMakeLists.txt | Out-Null
} else {
    git add generated/CMakeLists.txt   # stages the on-disk deletion
}

Write-Host "3. Updating README.md..." -ForegroundColor Cyan
$readmePath = "README.md"
if (Test-Path $readmePath) {
    $readme = Get-Content $readmePath -Raw
    $before = $readme

    $readme = $readme -replace `
        '(?s)Not required to build.{0,20}checked in\. Prefer\s*\r?\n\s*`\$env:LOGICMAKE_ROOT`[^\r\n]*\r?\n\s*"Build system" below for why\.', `
        ('**Required** to build -- `generated/CMakeLists.txt` is gitignored, ' + `
         'not checked in, and must be regenerated. Prefer `$env:LOGICMAKE_ROOT` ' + `
         'over relying on a bare `logimake` on PATH; see "Build system" below for why.')

    $readme = $readme -replace `
        '(?s)A checked-in copy of\s*\r?\n\s*`generated/CMakeLists\.txt` ships in this archive[^\r\n]*\r?\n[^\r\n]*out of the box even without CppLogicMake installed[^\r\n]*\r?\n[^\r\n]*automatically when `\$env:LOGICMAKE_ROOT` is set[^\r\n]*\r?\n[^\r\n]*`logimake` on PATH\)\.', `
        ('`generated/CMakeLists.txt` is a build artifact, gitignored rather ' + `
         'than committed, and regenerated by `s.ps1` on every build -- so ' + `
         'CppLogicMake is a hard prerequisite (see "Prerequisites" above), ' + `
         'not an optional convenience.')

    if ($readme -eq $before) {
        Write-Warning "README.md text didn't match the expected passages -- edit those two paragraphs by hand (search for 'checked in' / 'checked-in copy')."
    } else {
        Set-Content $readmePath $readme -NoNewline
        Write-Host "   README.md updated." -ForegroundColor DarkGray
    }
}

Write-Host "4. Updating s.ps1 fallback message..." -ForegroundColor Cyan
$sPath = "s.ps1"
if (Test-Path $sPath) {
    $s = Get-Content $sPath -Raw
    $before = $s
    $s = $s -replace 'checked-in (file|copy)', 'nothing -- configure will fail with a clear missing-file error, since generated/CMakeLists.txt is no longer committed'
    if ($s -ne $before) {
        Set-Content $sPath $s -NoNewline
        Write-Host "   s.ps1 updated." -ForegroundColor DarkGray
    } else {
        Write-Warning "s.ps1 fallback text didn't match -- check its 'checked-in' warning message by hand."
    }
}

Write-Host "`nDone. Review the diff, then commit when it looks right:" -ForegroundColor Green
git status
